### ISSUE TITLE
Qualcomm Atheros, AR9285 Wireless Network Adapter (PCI-Express)

### ISSUE THREAD

**Issue by JahWorks** [RehabMan/OS-X-BrcmPatchRAM#13]
Hi pike. I  use clover and I have one Atheros Vendor 168C, DEV 002B, SUBVENDOR 106B, SUBDEV 008F and i installed the 2 kexts:

BrcmPatchRAM2 and BrcmFirmwareData in clover EFI kexts but i cant sucess with the bluetooth.

And funny that already installed it in the version of 10.11.3 but not tested:

http://cl.ly/fiZe/bluetooth%20works%2010.11.jpg

I att my ioreg 
![bluetooth works 10 11](https://cloud.githubusercontent.com/assets/5008946/14574378/ae1cb4be-0331-11e6-99ba-ed80472c2668.jpg)
[G75vw bios 202.zip](https://github.com/RehabMan/OS-X-BrcmPatchRAM/files/221747/G75vw.bios.202.zip)

**Comment by RehabMan** [comment]
This driver is for Broadcom BT, not Atheros.

BTW, I don't answer to 'Pike'.

**Comment by JahWorks** [comment]
Sorry! it was a mistake, RehabMan.
The driver is Broadcom as you said.
The bluetooth works in pref. pane but the icon is offline
![screen shot 2016-04-28 at 02 52 38](https://cloud.githubusercontent.com/assets/5008946/14876555/667f1cf4-0cec-11e6-8302-29f5dd1ea5de.png)
![screen shot 2016-04-28 at 02 52 49](https://cloud.githubusercontent.com/assets/5008946/14876556/6682b8d2-0cec-11e6-8745-9623ac591553.png)
![screen shot 2016-04-28 at 02 52 53](https://cloud.githubusercontent.com/assets/5008946/14876557/6684e17a-0cec-11e6-8933-ae2123932dfb.png)

Thanks!! RehabMan
