### ISSUE TITLE
/S/L/E vs /L/E

### ISSUE THREAD

**Issue by ylluminate** [RehabMan/OS-X-BrcmPatchRAM#17]
I'm curious, I have been wondering if this driver would be more resilient to system updates if we were to place it into `/Library/Extensions` vs the current recommendation of `/System/Library/Extensions`, especially on native Mac installs. 

What's the situation on this, is this not a possibility?

**Comment by RehabMan** [comment]
For 10.11, your choice.
No difference either way regarding "resiliency to updates".

**Comment by ylluminate** [comment]
Thanks, I have this strange fear / suspicion that Apple is going to start purging /S/L/E on updates in the very near future due to the SIP flutterings, etc.
