### ISSUE TITLE
Continuity not working on T430

### ISSUE THREAD

**Issue by phen0menal** [RehabMan/OS-X-BrcmPatchRAM#25]
I'm using a T430 through the el capitan guide off tonymacx86 and the Intel 6205's Broadcom Bluetooth works with your kext just fine. I don't have a hacked BIOS since I don't have the necessary tools for it but I'm using USB WiFi as a good solution for now. I can't seem to get Instant HotSpot or Handoff working at all.

Broadcom Chip Name: BCM20702A3
Product ID: 8678
Vendor ID: 2652

Output from System Information:

  Apple Bluetooth Software Version:	5.0.2f4
  Hardware, Features, and Settings:
  Name:	Lenovo ThinkBook Pro (T430)
  Address:	e0-06-e6-ba-e3-12
  Bluetooth Low Energy Supported:	Yes
  Handoff Supported:	No
  Instant Hot Spot Supported:	No
  Manufacturer:	Broadcom
  Transport:	USB
  Chipset:	20702A3
  Firmware Version:	v14 c5853
  Bluetooth Power:	On
  Discoverable:	On
  Connectable:	Yes
  Auto Seek Pointing:	On
  Remote wake:	On
  Vendor ID:	0x0A5C
  Product ID:	0x21E6
  HCI Version:	4.1 (0x7)
  HCI Revision:	0x16DD
  LMP Version:	4.1 (0x7)
  LMP Subversion:	0x220E
  Device Type (Major):	Computer
  Device Type (Complete):	Mac Portable
  Composite Class Of Device:	0x38010C
  Device Class (Major):	0x01
  Device Class (Minor):	0x03
  Service Class:	0x1C0
  Auto Seek Keyboard:	On
  Devices (Paired, Configured, etc.):
  Metal-E:
  Address:	04-4B-ED-53-73-1B
  Major Type:	Phone
  Minor Type:	Smartphone
  Services:	Phonebook, PAN Network Access Profile, AVRCP Device, Handsfree Gateway, Audio Source, MAP MAS-iOS, Wireless iAP, AVRCP Device
  Paired:	Yes
  Configured:	Yes
  Connected:	No
  Manufacturer:	Broadcom (0x8, 0x6607)
  Firmware Version:	0x0A20
  Vendor ID:	0x004C
  Product ID:	0x6F02
  Class of Device:	0x02 0x03 0x7A020C
  EDR Supported:	Yes
  eSCO Supported:	Yes
  SSP Supported:	Yes
  Services:
  Bluetooth File Transfer:
  Folder other devices can browse:	/Users/phen0m/Public
  When receiving items:	Accept all without warning
  State:	Enabled
  Bluetooth File Exchange:
  Folder for accepted items:	/Users/phen0m/Downloads
  When other items are accepted:	Save to location
  When receiving items:	Accept all without warning
  State:	Enabled
  Bluetooth Internet Sharing:
  State:	Disabled
  Incoming Serial Ports:
  Bluetooth-Incoming-Port:
  RFCOMM Channel:	3
  Requires Authentication:	No
  Outgoing Serial Ports:
  Metal-E-WirelessiAP:
  Address:	04-4B-ED-53-73-1B
  RFCOMM Channel:	1
  Requires Authentication:	No

**Comment by RehabMan** [comment]
Handoff/hotspot requires a patch to IOBluetoothFamily. You clearly did not apply it.
It is not related to this kext, which just loads firmware.
