### ISSUE TITLE
12.0.1.750 Drivers

### ISSUE THREAD

**Issue by Rashed97** [RehabMan/OS-X-BrcmPatchRAM#26]
Hi Rehabman,

Just thought I'd let you know that there's newer drivers available (version 12.0.1.750) on Dell's site: http://www.dell.com/support/home/us/en/19/Drivers/DriversDetails?driverId=YW21W&fileId=3596400500&osCode=WT64A&productCode=xps-15-9550-laptop&languageCode=en&categoryId=NI

**Comment by RehabMan** [comment]
I usually sync from station-drivers.com.

**Comment by RehabMan** [comment]
Latest version on station-drivers.com is 12.0.1.921, which is the version I last synced to.
