### ISSUE TITLE
BCM2045A0 can not work

### ISSUE THREAD

**Issue by skinnyshy** [RehabMan/OS-X-BrcmPatchRAM#27]
Hi RehabMan ,I use `BrcmFirmwareData.kext`  `BrcmPatchRAM2.kext` and `USBInjectAll.kext` in my clover\kexts\others ,BTW my laptop is DELL XPS 15 9550 UHD installed osx 10.11.6 , and I found the bluetooth is unusual,sometimes it works ,but  when I reboot the laptop,it dosen't work.   
<img width="910" alt="2017-03-01 16 05 19" src="https://cloud.githubusercontent.com/assets/12553514/23451447/eba12d6e-fe9a-11e6-9f59-aa5a37d7b885.png">
<img width="244" alt="2017-02-28 17 12 32" src="https://cloud.githubusercontent.com/assets/12553514/23451539/495e32bc-fe9b-11e6-9b07-b4a75180f39b.png">

**Comment by RehabMan** [comment]
The issues database is not the correct place to troubleshoot your issue.
Use the forums.
