### ISSUE TITLE
BCM4356

### ISSUE THREAD

**Issue by willin** [RehabMan/OS-X-BrcmPatchRAM#31]
does it compatible?

**Comment by RehabMan** [comment]
It depends on your bluetooth hardware (BCM4356 specifies only WiFi).
Note that BCM4356 WiFi is not supported.

**Comment by willin** [comment]
Is there a tablet(like ipad pro, surface pro, huawei matebook) can run osx perfectly?

**Comment by RehabMan** [comment]
The Apple iPad Pro runs iOS perfectly.
No such thing as a perfect hackintosh.

**Comment by willin** [comment]
@RehabMan 'coz i need a coding env... (using node.js and mysql)

I've been looking into it for a long time, most tablets WIFI/BT not work perfectly

In fact, everything else is bearable

**Comment by RehabMan** [comment]
Off-topic here.
