### ISSUE TITLE
BCM20702A0 Failed to write to bulk pipe

### ISSUE THREAD

**Issue by 5h4rk1337** [RehabMan/OS-X-BrcmPatchRAM#34]
I have a Problem with a BCM20702A0 USB Dongle.

Device product ID   0x21ec
Device vendor ID   0x0a5c  (Broadcom Corp.)
BrcmPatchRAM version used   RehabMan-BrcmPatchRAM-2016-0705

Syslog:
Aug 31 19:26:03 Karmas-Mac-Pro kernel[0]: BrcmPatchRAM2: Version 2.2.7 starting on OS X Darwin 15.6.
Aug 31 19:26:03 Karmas-Mac-Pro kernel[0]: BrcmPatchRAM2: Published new IOKit personality for BrcmFirmwareStore.
Aug 31 19:26:03 Karmas-Mac-Pro kernel[0]: BrcmPatchRAM2: Published new IOKit personality for BrcmPatchRAMResidency.
Aug 31 19:26:03 Karmas-Mac-Pro kernel[0]: BrcmPatchRAM: Loaded firmware "BCM20702A1_001.002.014.1443.1460_v5556.zhx" from resources.
Aug 31 19:26:03 Karmas-Mac-Pro kernel[0]: BrcmPatchRAM: Decompressed firmware (29555 bytes --> 69721 bytes).
Aug 31 19:26:03 Karmas-Mac-Pro kernel[0]: BrcmPatchRAM: Firmware is valid IntelHex firmware.
Aug 31 19:26:03 Karmas-Mac-Pro kernel[0]: BrcmPatchRAM2: [0a5c:21ec]: USB [0019860023F6 v274] "BCM20702A0" by "Broadcom Corp"
Aug 31 19:26:03 Karmas-Mac-Pro kernel[0]: BrcmPatchRAM2: [0a5c:21ec]: Firmware upgrade completed successfully.
Aug 31 19:26:03 Karmas-Mac-Pro kernel[0]: BrcmPatchRAM2: [0a5c:21ec]: Published new IOKit personality.
Aug 31 19:26:03 Karmas-Mac-Pro kernel[0]: BrcmPatchRAM2: Processing time 0.130 seconds.
Aug 31 19:26:04 Karmas-Mac-Pro kernel[0]: BrcmPatchRAM2: Version 2.2.7 starting on OS X Darwin 15.6.
Aug 31 19:26:04 Karmas-Mac-Pro kernel[0]: BrcmPatchRAM2: [0a5c:21ec]: USB [0019860023F6 v274] "BCM20702A0" by "Broadcom Corp"
Aug 31 19:26:32 Karmas-Mac-Pro kernel[0]: BrcmPatchRAM2: [0a5c:21ec]: Failed to write to bulk pipe ("0xe00002ed (UNDEFINED)" 0xe00002ed).
Aug 31 19:26:33 Karmas-Mac-Pro kernel[0]: BrcmPatchRAM2: [0a5c:21ec]: Not responding - Delaying next read.
Aug 31 19:26:33 Karmas-Mac-Pro kernel[0]: BrcmPatchRAM2: [0a5c:21ec]: Failed to write to bulk pipe ("0xe00002d8 (UNDEFINED)" 0xe00002d8).
Aug 31 19:26:33 Karmas-Mac-Pro kernel[0]: BrcmPatchRAM2: [0a5c:21ec]: continuousRead - Failed to queue read (0xe00002d8)
Aug 31 20:30:06 Karmas-Mac-Pro com.apple.kextcache[747]: kext-dev-mode allowing invalid signature -67062 0xFFFFFFFFFFFEFA0A for kext BrcmFirmwareRepo.kext

**Comment by RehabMan** [comment]
Use the forums for troubleshooting your issue.  This section is for confirmed/investigated bug reports only.

My guess: You have Google Chrome or Android File Transfer hooking your USB ports.  You can find info in my laptop FAQ:
https://www.tonymacx86.com/threads/faq-read-first-laptop-frequent-questions.164990/
