### ISSUE TITLE
Bluetooth Keyboard in Clover

### ISSUE THREAD

**Issue by Ralle** [RehabMan/OS-X-BrcmPatchRAM#37]
Hey RehabMan,

You are doing the hackintosh community a huge service. Keep up the great work!

I have this build https://pcpartpicker.com/list/k6wJXH along with an NGFF BCM94352Z DW1560 card.

I have installed the following in /System/Library/Extensions:
BrcmPatchRAM2.kext
BrcmFirmwareRepo.kext

And this in /Library/Extensions:
FakePCIID.kext
FakePCIID_Broadcom_WiFi.kext

It works perfectly when booted in macOS 10.12.6 but the keyboard does not work in the Clover menu. Am I missing something?

**Comment by RehabMan** [comment]
That is a BIOS issue. Kexts cannot help prior to booting the OS.
