### ISSUE TITLE
Could not turn on Bluetooth again when turn off

### ISSUE THREAD

**Issue by diepnt90** [RehabMan/OS-X-BrcmPatchRAM#39]
Hi,

my bluetooth is running normally but when I turn off it , then I could not turn on again. . the bluetooth icon always show "on"  but there is no bluetooth. need to restart to turn on

also handoff, airdrop working but some application using bluetooth to pair ipphone like Macid, Nearlock did not recognize my iphone/ipad.

please help me to check that

**Comment by RehabMan** [comment]
Use the forums.
