### ISSUE TITLE
Bluetooth on the module BCM943602BAED DW1830

### ISSUE THREAD

**Issue by walkman2021** [RehabMan/OS-X-BrcmPatchRAM#40]
[MacBook Pro — Константин.zip](https://github.com/RehabMan/OS-X-BrcmPatchRAM/files/1366752/MacBook.Pro.zip)
Hello RehabMan please add support Bluetooth: BCM20703A1  0a5c:6410
Although the resources present BCM20703A1 firmware / BrcmPatchRAM does not load it.
I put  io registry

**Comment by walkman2021** [comment]
[New_Bt_firmware_BCM20703A1.zip](https://github.com/RehabMan/OS-X-BrcmPatchRAM/files/1366756/New_Bt_firmware_BCM20703A1.zip)

**Comment by RehabMan** [comment]
Support for 0a5c:6410 already present.
Firmwares are updated automatically from Windows drivers via firmware.rb.
Last/latest drivers I know of on station-drivers: http://www.station-drivers.com/index.php?option=com_remository&Itemid=352&func=fileinfo&id=2130&lang=en

**Comment by walkman2021** [comment]
Strangely, since the 5th time the firmware has booted, but the bluetooth does not work properly and the bluetooth does not see the device

**Comment by RehabMan** [comment]
Use the forums.
