### ISSUE TITLE
Broadcom博通BCM 2070/20702系列蓝牙驱动12.0.1.750版

### ISSUE THREAD

**Issue by hkbase** [RehabMan/OS-X-BrcmPatchRAM#41]
新版本的博通驱动
http://file5.mydrivers.com/2015/Bluetooth/broadcom_bluetooth_12_0_1_750_64bit.zip

**Comment by RehabMan** [comment]
This kext was last synced to 921: http://www.station-drivers.com/index.php?option=com_remository&Itemid=352&func=fileinfo&id=2130&lang=en

AFAIK, no newer drivers than 921.
