### ISSUE TITLE
Possibility to connect to more then one device

### ISSUE THREAD

**Issue by staminna** [RehabMan/OS-X-BrcmPatchRAM#46]
Hi

Thanks you so much for the software.
I bought a Microsoft Sculpt Ergonomic Keyboard (Bluetooth 4.0) and a external Trackpad but my Macbook Pro (early 2011 / HIgh Sierra - Bluetooth 2.0) couldn't connect to the keyboard, so I bought a Asus USB-400 and I can't seem to be able to use both devices at the same time. Is it impossible by design, or do you think there is something I can do, perhaps buying another USB dongle?

Thanks,
Jorge,

**Comment by RehabMan** [comment]
No idea.  Sounds like a hardware specific/compatibility issue.
You should contact Apple...
