### ISSUE TITLE
BrcmPatch for Bluetooth not working on 10.13.6

### ISSUE THREAD

**Issue by dr3nan** [RehabMan/OS-X-BrcmPatchRAM#51]
Hello there!

I just moved to 13.6 from a stable 13.5 on a Asus Z370G WiFi AC and the bluetooth has stoped working. I have a DW1560 which uses a BCM94352Z through a ngff M.2 on the board and so far since 10.13.3 I had no issues. At first I thought it might be the new USB port patch, which I added the new one, with no luck.

I have gone back to 13.5 on another identical build and bluetooth is back on. How could we solve this issue?

I attach two ioreg, one with 13.5 and another with 13.6
[Archive 2.zip](https://github.com/RehabMan/OS-X-BrcmPatchRAM/files/2205117/Archive.2.zip)

**Comment by RehabMan** [comment]
Your USB configuration is not correct.
See guide:
https://www.tonymacx86.com/threads/guide-creating-a-custom-ssdt-for-usbinjectall-kext.211311/
