### ISSUE TITLE
DW 1820A can not connect bluetooth keyboard stable

### ISSUE THREAD

**Issue by cattyhouse** [RehabMan/OS-X-BrcmPatchRAM#52]
Chip: DW1820A (BCM94350ZAE_2)

Vendor ID:	0x0A5C
Product ID:	0x6414
Firmware Version:	v7 c6820
Connectable:	Yes
Discoverable:	On
Remote wake: On

Installed and loaded kext in /L/E :
com.no-one.BrcmFirmwareStore (2.2.10)
com.no-one.BrcmPatchRAM2 (2.2.10)
macOS version 10.13.6

I was able to connect and use a bluetooth keyboard for nearly 2 hours the first time I installed those drivers along with USBInjectAll.kext, then after a reboot, the bluetooth can still search devices around, but my keyboard keeps connect and then disconnect, I tested this keyboard on my MacBook Air, it has no problem by itself. 

I also tried bluetooth headphone, keeps connecting and disconnecting. But Airdrop works perfect with my iPhone and MacBook, wifi also native no kexts needed.

what is the possible issue? what more information can I provide?

**Comment by RehabMan** [comment]
Use the forums.  This is not the appropriate place to troubleshoot your issue.
