### ISSUE TITLE
Can I use this BRCMPatchRAM for Edimax Wi-Fi N150 Bluetooth4.0 USB Adapter on Hackintosh mac OS High Sierra

### ISSUE THREAD

**Issue by gmansata6290** [RehabMan/OS-X-BrcmPatchRAM#53]
Device Details : Edimax Wi-Fi N150 Bluetooth4.0 USB Adapter:

  Product ID:	0xa611
  Vendor ID:	0x7392
  Version:	2.00
  Serial Number:	00e04c000001
  Speed:	Up to 480 Mb/sec
  Manufacturer:	Realtek
  Location ID:	0x1a110000 / 2
  Current Available (mA):	500
  Current Required (mA):	500
  Extra Operating Current (mA):	0

WIFI is working perfectly only bluetooth is not working...

**Comment by RehabMan** [comment]
BrcmPatchRAM, unsurprisingly, is for Broadcom PatchRAM devices only.
