### ISSUE TITLE
Foxconn 0x0489:0xe07a

### ISSUE THREAD

**Issue by hpbrownfr** [RehabMan/OS-X-BrcmPatchRAM#55]
hi
is there any chance to see this version supported?
thanks

**Comment by RehabMan** [comment]
Is it actually a patchRAM device?
Does it have firmware files in current Windows drivers?

**Comment by hpbrownfr** [comment]
Yes it has a firmware file and is a PatchRAM device. In fact the kext was not installed properly. It’s working now. Issue can be closed
