### ISSUE TITLE
BRCM 6410 Working After Installing BrcmPatchRAM2 to /S/L/E

### ISSUE THREAD

**Issue by bliles** [RehabMan/OS-X-BrcmPatchRAM#56]
Just thought I'd let you know that I can confirm that the following is working on 10.13.6 using BrcmPatchRAM2 and BrcmFirmwareRepo.

Product ID: 0x6410
Vendor ID: 0x0a5c

I couldn't get it to work until I installed BrcmPatchRAM2 to /System/Library/Extensions. Injecting with Clover did not work. I have BrcmFirmwareRepo installed to /Library/Extensions.

**Comment by RehabMan** [comment]
All non-Apple/hack kexts on 10.11 and later go to /L/E, not /S/L/E.
