### ISSUE TITLE
Problem Bluetooth with Wi-Fi 2.4GHz, Broadcom BCM943602 NGFF

### ISSUE THREAD

**Issue by boesbo** [RehabMan/OS-X-BrcmPatchRAM#60]
Thank you for this project.
I have a problem with my Broadcom BCM943602 NGFF card on Mojave 10.14.1.
I entered the kext: "BrcmFirmwareData.kext" and "BrcmPatchRAM2.kext" in Clover and everything works fine.

Only when the Wi-Fi connects to a 2.4GHz network the bluetooth devices start to have big problems, the AirPods are bad and the trackpad jerks.

I tested with the same PC by booting Windows 10 and I do not have this problem.
I did a further test with the same 2.4GHz network and the same bluetooth devices on my MacBook Pro 2015 with the same version of Mojave, and I do not have these problems.

**Comment by RehabMan** [comment]
No ideas for you... other than to use a 5ghz network for WiFi.
