### ISSUE TITLE
Personal Hotspot (with iPhone) not working on Mojave (DW1560)

### ISSUE THREAD

**Issue by RicKrauel** [RehabMan/OS-X-BrcmPatchRAM#65]
First thanks for your work.

I have the DW1560 installed, AirDrop, Handoff and normal Bluetooth streaming working fine.

The Personal Hotspot (with my iCloud iPhone) is not usable however. I texted someone on tonymacx86 running the same setup but with High Sierra and everything works in his system. 

Was there a change regarding this in Mojave?

**Comment by RehabMan** [comment]
Instant hotspot has never worked very well on non-Apple hardware, and seems to get worse with each release.
